"""adding multis

Revision ID: 26b2b9b2d6f
Revises: 47a82926385b
Create Date: 2014-12-06 16:14:07.802276

"""

# revision identifiers, used by Alembic.
revision = '26b2b9b2d6f'
down_revision = '47a82926385b'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_polygon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('multipolygon', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=2802), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multi_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('multipoint', geoalchemy2.types.Geometry(geometry_type='MULTIPOINT', srid=926919), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('collection', geoalchemy2.types.Geometry(geometry_type='GEOMETRYCOLLECTION', srid=4326), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multi_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('multiline', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=32010), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('spatial_ref_sys')
    #op.drop_index('idx_POI_point', table_name='POI')
    #op.drop_index('idx_line_line', table_name='line')
    #op.drop_index('idx_polygon_polygon', table_name='polygon')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_polygon_polygon', 'polygon', ['polygon'], unique=False)
    #op.create_index('idx_line_line', 'line', ['line'], unique=False)
    #op.create_index('idx_POI_point', 'POI', ['point'], unique=False)
    #op.create_table('spatial_ref_sys',
    #sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    #sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    #sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    #)
    op.drop_table('multi_line')
    op.drop_table('collection')
    op.drop_table('multi_point')
    op.drop_table('multi_polygon')
    ### end Alembic commands ###
