"""initial creation

Revision ID: 397b837e842d
Revises: None
Create Date: 2014-12-06 08:32:37.457688

"""

# revision identifiers, used by Alembic.
revision = '397b837e842d'
down_revision = None

from alembic import op
import sqlalchemy as sa
import flask_admin


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('POI',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('point', flask_admin.contrib.geoa.sqltypes.Geometry(geometry_type='POINT', srid=926919), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('spatial_ref_sys')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('spatial_ref_sys',
    #sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    #sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    #sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    #sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    #)
    op.drop_table('POI')
    ### end Alembic commands ###
